### ISSUE TITLE
test your example

### ISSUE THREAD

**Issue by maralzar** [kasrahabib/persian-sentiment-analysis#1]
I test your example model but I got wrong label for your exact example.

```python
predict_sentiment('می تواند به همین دلیل از آن متنفر باشد', return_class_label = True)
output:
1
```

**Comment by kasrahabib** [comment]
Hi @maralzar,

Thanks for sharing. 
Can you remove the ```return_class_label = True```, re-run it and see if the output changes.

**Comment by maralzar** [comment]
> Hi @maralzar,
> 
> Thanks for sharing.
> Can you remove the `return_class_label = True`, re-run it and see if the output changes.

Thanks it solved
